# Generated by Django 5.2.6 on 2025-09-15 13:31

import apps.integrations.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalDataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('platform', models.CharField(choices=[('hdx', 'Humanitarian Data Exchange'), ('iom_dtm', 'IOM Displacement Tracking Matrix'), ('unhcr', 'UNHCR Refugee Data'), ('fts', 'OCHA Financial Tracking Service'), ('who', 'WHO Health Data'), ('acaps', 'ACAPS Analysis'), ('wfp', 'World Food Programme'), ('fews_net', 'FEWS NET')], max_length=20)),
                ('api_endpoint', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('sync_frequency_hours', models.PositiveIntegerField(default=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'integrations_external_data_source',
            },
        ),
        migrations.CreateModel(
            name='DataSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_start', models.DateTimeField()),
                ('sync_end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial Success')], max_length=20)),
                ('records_processed', models.PositiveIntegerField(default=0)),
                ('records_created', models.PositiveIntegerField(default=0)),
                ('records_updated', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('date_from', models.DateField(default=apps.integrations.models.get_crisis_start_date)),
                ('date_to', models.DateField(default=apps.integrations.models.get_current_date)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.externaldatasource')),
            ],
            options={
                'db_table': 'integrations_data_sync_log',
                'ordering': ['-sync_start'],
            },
        ),
        migrations.CreateModel(
            name='SudanCrisisData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('displacement', 'Displacement & Population'), ('food_security', 'Food Security'), ('health', 'Health & Disease'), ('funding', 'Humanitarian Funding'), ('conflict', 'Conflict & Security'), ('access', 'Humanitarian Access'), ('needs', 'Humanitarian Needs Assessment')], max_length=20)),
                ('external_id', models.CharField(help_text='ID from external system', max_length=200)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('crisis_date', models.DateField(help_text='Date relevant to Sudan crisis (from 2023-04-15)')),
                ('report_date', models.DateField(help_text='Date when data was reported/published')),
                ('admin_level', models.CharField(blank=True, help_text='Admin 0, 1, 2, etc.', max_length=20)),
                ('location_name', models.CharField(blank=True, max_length=200)),
                ('location_code', models.CharField(blank=True, max_length=50)),
                ('raw_data', models.JSONField(help_text='Original JSON data from external API')),
                ('processed_data', models.JSONField(blank=True, help_text='Processed/normalized data', null=True)),
                ('url', models.URLField(blank=True, help_text='Source URL')),
                ('tags', models.JSONField(default=list, help_text='Tags for categorization')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.externaldatasource')),
            ],
            options={
                'db_table': 'integrations_sudan_crisis_data',
            },
        ),
        migrations.CreateModel(
            name='RefugeeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refugees', models.PositiveIntegerField(blank=True, null=True)),
                ('asylum_seekers', models.PositiveIntegerField(blank=True, null=True)),
                ('returnees', models.PositiveIntegerField(blank=True, null=True)),
                ('country_of_origin', models.CharField(blank=True, max_length=100)),
                ('country_of_asylum', models.CharField(blank=True, max_length=100)),
                ('demographics', models.JSONField(default=dict)),
                ('crisis_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.sudancrisisdata')),
            ],
            options={
                'db_table': 'integrations_refugee_data',
            },
        ),
        migrations.CreateModel(
            name='HealthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_facilities_functional', models.PositiveIntegerField(blank=True, null=True)),
                ('health_facilities_total', models.PositiveIntegerField(blank=True, null=True)),
                ('disease_name', models.CharField(blank=True, max_length=100)),
                ('cases_reported', models.PositiveIntegerField(blank=True, null=True)),
                ('deaths_reported', models.PositiveIntegerField(blank=True, null=True)),
                ('people_in_need_health', models.PositiveIntegerField(blank=True, null=True)),
                ('people_reached_health', models.PositiveIntegerField(blank=True, null=True)),
                ('crisis_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.sudancrisisdata')),
            ],
            options={
                'db_table': 'integrations_health_data',
            },
        ),
        migrations.CreateModel(
            name='FundingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirements', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('funding_received', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('funding_gap', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('donor_country', models.CharField(blank=True, max_length=100)),
                ('recipient_organization', models.CharField(blank=True, max_length=200)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('appeal_name', models.CharField(blank=True, max_length=300)),
                ('crisis_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.sudancrisisdata')),
            ],
            options={
                'db_table': 'integrations_funding_data',
            },
        ),
        migrations.CreateModel(
            name='DisplacementData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idp_individuals', models.PositiveIntegerField(blank=True, null=True)),
                ('idp_families', models.PositiveIntegerField(blank=True, null=True)),
                ('returnee_individuals', models.PositiveIntegerField(blank=True, null=True)),
                ('returnee_families', models.PositiveIntegerField(blank=True, null=True)),
                ('departure_location', models.CharField(blank=True, max_length=200)),
                ('arrival_location', models.CharField(blank=True, max_length=200)),
                ('site_type', models.CharField(blank=True, max_length=100)),
                ('site_name', models.CharField(blank=True, max_length=200)),
                ('crisis_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.sudancrisisdata')),
            ],
            options={
                'db_table': 'integrations_displacement_data',
            },
        ),
        migrations.AddIndex(
            model_name='sudancrisisdata',
            index=models.Index(fields=['data_type', 'crisis_date'], name='integration_data_ty_c535ab_idx'),
        ),
        migrations.AddIndex(
            model_name='sudancrisisdata',
            index=models.Index(fields=['source', 'external_id'], name='integration_source__eab969_idx'),
        ),
        migrations.AddIndex(
            model_name='sudancrisisdata',
            index=models.Index(fields=['crisis_date'], name='integration_crisis__bb336d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sudancrisisdata',
            unique_together={('source', 'external_id')},
        ),
    ]
