# Generated by Django 5.2.6 on 2025-09-13 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0004_remove_site_families_remove_site_population_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Assessment title', max_length=255)),
                ('title_ar', models.CharField(blank=True, help_text='Assessment title in Arabic', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Assessment description')),
                ('assessment_type', models.CharField(choices=[('rapid', 'Rapid Assessment'), ('detailed', 'Detailed Assessment'), ('needs', 'Needs Assessment'), ('monitoring', 'Monitoring & Evaluation'), ('baseline', 'Baseline Assessment')], default='rapid', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('kobo_form_id', models.CharField(blank=True, help_text='Kobo form asset ID', max_length=255)),
                ('kobo_form_url', models.URLField(blank=True, help_text='Direct link to Kobo form')),
                ('kobo_username', models.CharField(blank=True, help_text='Kobo username for API access', max_length=255)),
                ('start_date', models.DateField(blank=True, help_text='Assessment start date', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Assessment end date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ManyToManyField(blank=True, help_text='Users assigned to conduct this assessment', related_name='assigned_assessments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_assessments', to=settings.AUTH_USER_MODEL)),
                ('target_sites', models.ManyToManyField(blank=True, help_text='Sites where this assessment should be conducted', related_name='assessments', to='sites.site')),
            ],
        ),
        migrations.CreateModel(
            name='KoboIntegrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kobo_server_url', models.URLField(default='https://kf.kobotoolbox.org', help_text='Kobo server URL')),
                ('kobo_username', models.CharField(help_text='Kobo username', max_length=255)),
                ('kobo_api_token', models.CharField(help_text='Kobo API token', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kobo_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kobo_submission_id', models.CharField(blank=True, help_text='Kobo submission UUID', max_length=255)),
                ('kobo_data', models.JSONField(blank=True, help_text='Raw Kobo submission data', null=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('gps_location', models.JSONField(blank=True, help_text='GPS coordinates from mobile device', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assessments.assessment')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_responses', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_responses', to='sites.site')),
            ],
            options={
                'unique_together': {('assessment', 'site', 'respondent')},
            },
        ),
    ]
