# Generated by Django 5.2.6 on 2025-09-11 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_locality_state_site_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locality',
            name='center_point',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='center_point',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
