# Generated by Django 5.2.6 on 2025-09-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_locality_center_point_state_center_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='families',
        ),
        migrations.RemoveField(
            model_name='site',
            name='population',
        ),
        migrations.RemoveField(
            model_name='site',
            name='vulnerable_population',
        ),
        migrations.AddField(
            model_name='site',
            name='adults_18_59',
            field=models.PositiveIntegerField(blank=True, help_text='Adults between 18-59 years', null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='children_under_18',
            field=models.PositiveIntegerField(blank=True, help_text='Children under 18 years', null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='chronically_ill',
            field=models.PositiveIntegerField(blank=True, help_text='Number of chronically ill people', null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='disabled_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of people with disabilities', null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='elderly_60_plus',
            field=models.PositiveIntegerField(blank=True, help_text='Elderly 60+ years', null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='female_count',
            field=models.PositiveIntegerField(blank=True, help_text='Total female population', null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='male_count',
            field=models.PositiveIntegerField(blank=True, help_text='Total male population', null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='pregnant_women',
            field=models.PositiveIntegerField(blank=True, help_text='Number of pregnant women', null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='report_date',
            field=models.DateField(blank=True, help_text='Date when this data was reported/collected', null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='reported_by',
            field=models.CharField(blank=True, help_text='Name or organization that reported this data', max_length=255),
        ),
        migrations.AddField(
            model_name='site',
            name='size_of_location',
            field=models.CharField(blank=True, help_text="Physical size of the location (e.g., '5 hectares', 'Large', 'Small')", max_length=100),
        ),
        migrations.AddField(
            model_name='site',
            name='total_households',
            field=models.PositiveIntegerField(blank=True, help_text='Total number of households/families', null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='total_population',
            field=models.PositiveIntegerField(blank=True, help_text='Total number of people at the site', null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(help_text='Site name in English', max_length=255),
        ),
        migrations.AlterField(
            model_name='site',
            name='name_ar',
            field=models.CharField(blank=True, help_text='Site name in Arabic', max_length=255),
        ),
        migrations.AlterField(
            model_name='site',
            name='operational_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('planned', 'Planned'), ('closed', 'Closed')], default='active', help_text='Current operational status', max_length=20),
        ),
    ]
