# Generated by Django 5.2.6 on 2025-09-12 21:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0004_remove_site_families_remove_site_population_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('name_ar', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(default='#007bff', help_text='Hex color code', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FieldReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('text', 'Text Report'), ('voice', 'Voice Report'), ('image', 'Image Report'), ('mixed', 'Mixed Media Report')], default='text', max_length=20)),
                ('title', models.CharField(help_text='Brief report title', max_length=255)),
                ('text_content', models.TextField(blank=True, help_text='Text content of the report')),
                ('voice_file', models.FileField(blank=True, help_text='Voice recording (MP3, WAV, OGG, M4A)', upload_to='reports/voice/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg', 'm4a'])])),
                ('image_file', models.ImageField(blank=True, help_text='Supporting image', upload_to='reports/images/%Y/%m/')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('processing', 'AI Processing'), ('processed', 'Processed'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('location_coordinates', models.JSONField(blank=True, help_text='GPS coordinates where report was made', null=True)),
                ('ai_analysis', models.JSONField(blank=True, help_text='AI analysis results', null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_reports', to='sites.site')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Field Report',
                'verbose_name_plural': 'Field Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('demographic', 'Demographic Analysis'), ('needs_assessment', 'Needs Assessment'), ('risk_assessment', 'Risk Assessment'), ('resource_gap', 'Resource Gap Analysis'), ('sentiment', 'Sentiment Analysis')], max_length=20)),
                ('ai_confidence', models.FloatField(help_text='AI confidence score (0-1)')),
                ('analysis_data', models.JSONField(help_text='Structured analysis results')),
                ('extracted_entities', models.JSONField(blank=True, help_text='Named entities, numbers, locations', null=True)),
                ('key_insights', models.JSONField(blank=True, help_text='Key insights and recommendations', null=True)),
                ('model_version', models.CharField(help_text='AI model version used', max_length=50)),
                ('processing_time', models.FloatField(help_text='Processing time in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='reports.fieldreport')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('report', 'analysis_type')},
            },
        ),
        migrations.CreateModel(
            name='ReportTagging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField(default=1.0, help_text='Tagging confidence (0-1)')),
                ('auto_generated', models.BooleanField(default=False, help_text='Auto-generated by AI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='reports.fieldreport')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reports.reporttag')),
            ],
            options={
                'unique_together': {('report', 'tag')},
            },
        ),
    ]
